PROYECTO/PROYECTO/PROYECTO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("TIENDA.urls")),
    path('TIENDA/', include("TIENDA.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PROYECTO/PROYECTO/TIENDA/urls.py
from django.urls import path
from django.urls import path
from . import views

app_name = "TIENDA"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:producto_id>', views.producto, name="producto"),
    path('producto_alta/', views.producto_alta, name="producto_alta"),
    path('producto_editar/<int:producto_id>',
         views.producto_editar, name="producto_editar"),
    path('producto_eliminar/<int:producto_id>',
         views.producto_eliminar, name="producto_eliminar"),
    path('carrito/<int:producto_id>', views.carrito, name="carrito"),
    path('carrito/', views.carrito, name="carrito"),
    path('carrito_eliminar/<int:producto_id>',
         views.carrito_eliminar, name="carrito_eliminar"),
    path('carrito_eliminar/', views.carrito_eliminar, name="carrito_eliminar"),
    path('busqueda/<int:categoria_id>', views.buscador, name="buscador"),
    path('busqueda/', views.buscador, name="buscador"),
    path('acerca_de/', views.acerca_de, name="acerca_de"),
]

PROYECTO/PROYECTO/USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

PROYECTO/PROYECTO/TIENDA/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"


class Producto(models.Model):
    titulo = models.CharField(max_length=250, null=False)
    imagen = models.ImageField(upload_to='imagenes/')
    descripcion_producto = models.CharField(max_length=2000, null=False)
    precio = models.FloatField()
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, related_name="categoria_producto")

    def __str__(self):
        return f"{self.categoria} - {self.titulo} ({self.precio})"


class Carrito(models.Model):
    usuario = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="usuario")
    lista_productos = models.ManyToManyField(
        Producto, blank=True, null=True, related_name="carrito")
    total_carrito = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.usuario} - {self.lista_productos}"

PROYECTO/PROYECTO/TIENDA/forms.py
from django import forms
from .models import Producto


class FormProductoCustom(forms.ModelForm):

    # campos del modelo
    class Meta:
        model = Producto
        fields = ('titulo', 'categoria', 'precio',
                  'descripcion_producto', 'imagen')
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'titulo-pr'}),
            'precio': forms.TextInput(attrs={'class': 'precio-pr'}),
            'descripcion_producto': forms.Textarea(attrs={'class': 'descripcion-pr', 'id': 'id_descripcion'}),
            'imagen': forms.FileInput(attrs={'name': 'imagen_adjunta', 'class': 'imagen-pr'}),
        }

PROYECTO/PROYECTO/TIENDA/views.py
from functools import total_ordering
from TIENDA.models import Categoria
from TIENDA.models import Carrito
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db.models import Q

# Create your views here.


def index(request):
    if "carrito" not in request.session:
        request.session["carrito"] = []

    lista_productos = Producto.objects.all()
    # devuelvo la lista invertida
    lista_invertida = lista_productos[::-1]
    # elijo los ultimos 3 productos en una lista
    lista_imagenes = lista_invertida[0:3]
    # elijo los productos del 4 al 10
    lista_plana = lista_invertida[3:10]

    return render(request, "page/index.html", {
        "lista_productos_imagenes": lista_imagenes,
        "lista_productos": lista_plana,
        "lista_categorias": Categoria.objects.all(),
        "es_moderador": User.objects.filter(groups__name__in=['Moderador']),
        "carrito": request.session["carrito"],
    })


def producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    return render(request, "page/producto.html", {
        "producto": producto,
        "lista_categorias": Categoria.objects.all(),
        "es_moderador": User.objects.filter(groups__name__in=['Moderador'])
    })


@permission_required('TIENDA.add_producto')
def producto_alta(request):
    if request.method == "POST":
        #user = User.objects.get(username=request.user)
        form = FormProductoCustom(
            request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen']))
        if form.is_valid():
            form.save()
            return redirect("TIENDA:index")
    else:
        form = FormProductoCustom()
        return render(request, "page/producto_alta.html", {
            "form": form,
            "lista_categorias": Categoria.objects.all(),
        })


@permission_required('TIENDA.change_producto')
def producto_editar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":
        form = FormProductoCustom(
            data=request.POST, files=request.FILES, instance=un_producto)
        if form.is_valid():
            form.save()
            return redirect("TIENDA:index")
    else:
        form = FormProductoCustom(instance=un_producto)
        return render(request, 'page/producto_editar.html', {
            "form": form,
            # paso el producto para mostrar la imagen
            "producto": un_producto,
            # paso las categorias para el menu
            "lista_categorias": Categoria.objects.all(),
            "es_moderador": User.objects.filter(groups__name__in=['Moderador'])
        })


def producto_eliminar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    un_producto.delete()
    return redirect("TIENDA:index")


def buscador(request, categoria_id=""):
    if request.method == "POST":
        busqueda = request.POST['busqueda']
        # esta linea funciona
        # resultado = Producto.objects.filter(titulo__contains=busqueda)

        # el modulo Q permite me permite utilizar and/or en las consultas, distinct() me elimina las filas duplicadas
        resultado = Producto.objects.filter(Q(titulo__icontains=busqueda) | Q(
            descripcion_producto__icontains=busqueda)).distinct()

        return render(request, "page/busqueda.html", {
            "busqueda": busqueda,
            "resultado": resultado,
            "lista_categorias": Categoria.objects.all(),
            "es_moderador": User.objects.filter(groups__name__in=['Moderador'])
        })
    else:
        una_categoria = get_object_or_404(Categoria, id=categoria_id)
        queryset = Producto.objects.all()
        queryset = queryset.filter(categoria=una_categoria)
        return render(request, "page/busqueda.html", {
            "lista_categorias": Categoria.objects.all(),
            "lista_productos": queryset,
            "categoria_seleccionada": una_categoria,
            "es_moderador": User.objects.filter(groups__name__in=['Moderador'])

        })


def acerca_de(request):
    return render(request, "page/acerca_de.html", {
        "lista_categorias": Categoria.objects.all(),
        "es_moderador": User.objects.filter(groups__name__in=['Moderador'])
    })


@login_required
@permission_required('TIENDA.add_carrito')
def carrito(request, producto_id=''):

    if producto_id:
        carrito = Carrito.objects.filter(usuario=request.user.id).first()
        producto = Producto.objects.get(id=producto_id)

        # si existe el carrito y el usuario
        if carrito:
            if not producto in carrito.lista_productos.all():
                carrito.lista_productos.add(producto)
            else:
                carrito.lista_productos.remove(producto)

            # calculo el precio total
            total = 0
            for item in carrito.lista_productos.all():
                total += item.precio

            carrito.total_carrito = total

            # guardo el carrito
            carrito.save()

        else:
            usuario = User.objects.get(username=request.user)
            carrito = Carrito.objects.create(usuario=usuario)
            carrito.save()

            carrito.lista_productos.add(producto)
            carrito.total_carrito = producto.precio

        return render(request, "page/carrito.html", {
            "lista_categorias": Categoria.objects.all(),
            "lista_carrito": carrito.lista_productos.all(),
            "es_moderador": User.objects.filter(groups__name__in=['Moderador'])
        })
    else:
        carrito = Carrito.objects.filter(usuario=request.user.id).first()
        mensaje = ""

        if carrito:
            lista_carrito = carrito.lista_productos

            return render(request, "page/carrito.html", {
                "lista_categorias": Categoria.objects.all(),
                "lista_carrito": lista_carrito.all(),
                "es_moderador": User.objects.filter(groups__name__in=['Moderador']),
                "mensaje": mensaje
            })
        else:
            mensaje = "Todavia no a agregado ningun producto al carrito"

            return render(request, "page/carrito.html", {
                "lista_categorias": Categoria.objects.all(),
                "es_moderador": User.objects.filter(groups__name__in=['Moderador']),
                "mensaje": mensaje
            })


def carrito_eliminar(request, producto_id=""):
    if producto_id:
        carrito = Carrito.objects.filter(usuario=request.user.id).first()
        producto = Producto.objects.get(id=producto_id)

        for item in carrito.lista_productos.all():
            if item == producto:
                carrito.lista_productos.remove(item)

        lista_carrito = carrito.lista_productos

        return render(request, "page/carrito.html", {
            "lista_categorias": Categoria.objects.all(),
            "lista_carrito": lista_carrito.all(),
            "es_moderador": User.objects.filter(groups__name__in=['Moderador']),
        })

    else:
        carrito = Carrito.objects.filter(usuario=request.user.id).first()

        carrito.delete()

        mensaje = "Todavia no a agregado ningun producto al carrito"

        return render(request, "page/carrito.html", {
            "lista_categorias": Categoria.objects.all(),
            "es_moderador": User.objects.filter(groups__name__in=['Moderador']),
            "mensaje": mensaje,
        })

PROYECTO/PROYECTO/TIENDA/templates/page/acerca_de.html
{% extends "page/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col m-2">
            <p class="h2 text-center mb-4">
                Jaguarete KAA S.A
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-sm-12 m-auto">
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod adipisci dolore repudiandae deserunt ullam
                facere sunt rem quam, pariatur ipsum iusto odit repellat fuga quibusdam.
                Itaque consectetur dignissimos commodi aut.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam officia ipsa consectetur minima
                accusamus quod nihil quidem quaerat eveniet qui obcaecati eius cupiditate, porro sit similique mollitia
                vero facere necessitatibus.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus animi debitis quod odit quidem dolorem
                rerum ad nemo. Sunt, et harum ipsa tempora deserunt suscipit minima voluptatem possimus cum tempore.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque tempora vitae quae voluptate maxime
                voluptatum, aspernatur, eveniet quasi blanditiis perferendis accusamus labore quidem a optio.
            </p>
        </div>
    </div>
    {% endblock %}

PROYECTO/PROYECTO/TIENDA/templates/page/busqueda.html
{% extends "page/layout.html" %}
{% block content %}

{% if busqueda %}
<h1>Has buscado {{ busqueda }}</h1>
<ul>
    {% for coincidencia in resultado %}
    <li>
        <a href="{% url 'TIENDA:producto' coincidencia.id %}">
            {{coincidencia}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% if categoria_seleccionada%}
<h1>{{categoria_seleccionada}}</h1>
{% for producto in lista_productos %}
<li>
    <a href="{% url 'TIENDA:producto' producto.id %}">
        {{producto}}
    </a>
</li>
{% endfor %}
{% endif %}

{% endblock %}

PROYECTO/PROYECTO/TIENDA/templates/page/carrito.html
{% extends "page/layout.html" %}

{% block content %}

<div>
    <h2>{{ mensaje }}</h2>

    {% if lista_carrito %}

    {% for producto in lista_carrito %}
    <ul>
        <li>{{ producto.titulo }}<a role="button" class="btn btn-outline-danger btn-sm"
                href="{% url 'TIENDA:carrito_eliminar' producto.id %}">X</a></li>
    </ul>
    {% endfor %}
    <a role="button" class="btn btn-success btn-sm" href="{% url 'TIENDA:carrito_eliminar' %}">VACIAR CARRO</a>
    <a role="button" class="btn btn-success btn-sm" href="{% url 'TIENDA:index' %}">HOME</a>
    {% else %}
    <a role="button" class="btn btn-success btn-sm" href="{% url 'TIENDA:index' %}">HOME</a>

    {% endif %}

</div>

{% endblock %}

<h1>{{ variable }}</h1>

PROYECTO/PROYECTO/TIENDA/templates/page/index.html
{% extends "page/layout.html" %}
{% block content %}

<div class="row">
    {% for producto in lista_productos_imagenes %}

    <div class="col-md-4">

        <div class="card" style="width: 100%; margin: 5px;">
            <h4 class="text-center my-2"><ins>{{ producto.titulo }}</ins></h4>
            <img style="height: 20em;" src="{{producto.imagen.url}}" class="card-img-top">
            <div class="card-body" style="text-align: center;">
                <strong class="h5 mr-5">${{producto.precio|floatformat:2}}</strong>
                {% if user in es_moderador %}

                <a role="button" class="btn btn-warning btn-sm"
                    href="{% url 'TIENDA:producto_editar' producto.id %}">EDITAR</a>
                {% else %}

                <a role="button" class="btn btn-success btn-sm" href="{% url 'TIENDA:producto' producto.id %}">VER
                    PRODUCTO</a>
                {% endif %}
            </div>
        </div>

    </div>

    {% endfor %}
</div>

<h2 class="text-center my-5">MAS PRODUCTOS</h2>


<ul style="list-style:none">
    {% for producto in lista_productos %}
    <li>
        <div class="list-group my-2">

            {% if perms.TIENDA.change_producto %}
            <a href="{% url 'TIENDA:producto_editar' producto.id %}" class="list-group-item list-group-item-action">
                <img src="{{producto.imagen.url }}" class="rounded float-left mr-3" height="100px" width="100px">&nbsp;
                <h5>{{ producto.titulo }}</h5>
                {{producto.descripcion_producto |safe}}
            </a>
            {% else %}
            <a href="{% url 'TIENDA:producto' producto.id %}" class="list-group-item list-group-item-action">
                <img src="{{producto.imagen.url }}" class="rounded float-left mr-3" height="100px" width="100px">&nbsp;
                <h5>{{ producto.titulo }}</h5>
                {{producto.descripcion_producto |safe}}
            </a>
            {% endif %}

        </div>

    </li>

    {% endfor %}
</ul>

{% endblock %}

PROYECTO/PROYECTO/TIENDA/templates/page/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hace las compras de tus productos JAGUARETE sin moverte de tu casa" />
    <meta name="author" content="Labrador Brazda, Fernando Martin" />
    <title>JAGUARETE S.A.</title>
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://kit.fontawesome.com/ad87122803.js" crossorigin="anonymous"></script>
    <script src="{% static 'scripts.js' %}"></script>
</head>

<body>
    <div class="container d-flex flex-column min-vh-100">

        <!---- Header ----->
        <header>
            <div id="bloque_login">
                {% if user.is_authenticated %}
                ¡Hola!🖐 <b>{{ user.get_username }}</b> <a role="button" class="btn btn-outline-danger btn-sm"
                    href="{% url 'logout'%}?next={{request.path}}">SALIR</a>
                {% if user not in es_moderador %}
                <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'TIENDA:carrito' %}"><i
                        class="fas fa-shopping-cart mr-1"></i>CARRITO</a>
                {% endif %}
                {% else %}
                <a role="button" class="btn btn-outline-success btn-sm"
                    href="{% url 'login'%}?next={{request.path}}">ACCEDER</a>
                <a role="button" class="btn btn-outline-success btn-sm"
                    href="{% url 'USUARIOS:registrarse' %}">REGISTRO</a>
                {% endif %}
            </div>

            <h1 class="font-weight-bolder">JAGUARETE S.A.</h1>

        </header>

        <!---- Nav ----->

        <nav class="navbar navbar-expand-lg navbar-light bg-info mb-4">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'TIENDA:index' %}">
                            HOME
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <div class="dropdown">
                            <a type="button" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                CATEGORIAS
                            </a>
                            <div class="dropdown-menu bg-info mt-2">
                                {% for categoria in lista_categorias %}
                                <a class="dropdown-item bg-info" href="{% url 'TIENDA:buscador' categoria.id %}">
                                    {{ categoria }}</a>
                                {% endfor %}
                            </div>
                        </div>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'TIENDA:acerca_de' %}">
                            ACERCA DE
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="mailto:contacto@jaguarete-kaa.shop.ar">
                            CONTACTO
                        </a>
                    </li>
                    <li class="nav-item">
                        {% if perms.TIENDA.add_producto %}
                        <a class="nav-link" href="{% url 'TIENDA:producto_alta' %}">
                            <strong> + NUEVO PRODUCTO</strong>
                        </a>
                        {% endif %}
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'TIENDA:buscador'  %}">
                    {% csrf_token %}
                    <input name="busqueda" class="form-control mr-sm-2" type="search" placeholder="Buscar"
                        aria-label="Search">
                    <button class="btn btn-warning my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <!--- Footer ---->

        <footer class="footer mt-auto text-faded text-center py-2 bg-dark text-white">
            <div class="container">
                <p>&copy; Copyright 2021 Jaguarete Kaa SA, todos los derechos reservados. </p>
                <p class="m-auto">Design by <a href="https://github.com/Mhz-ar">Fernando M. Labrador B.</a>🧱</p>

            </div>
        </footer>
    </div>
</body>

</html>

PROYECTO/PROYECTO/TIENDA/templates/page/producto.html
{% extends "page/layout.html" %}
{% block content %}



<h2 class="text-center mt-1 mb-4">{{producto.titulo}}</h2>

<div class="row justify-content-center mb-4">
    <div class="col-12 col-md-9 noPadding">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12">
                <img style="height: 20em;" src="{{producto.imagen.url}}" class="card-img-top">
            </div>
            <div class="col-lg-6 col-md-6 col-12 d-flex flex-column justify-content-between">
                <div>
                    <p class="mt-5">
                        <b>CATEGORIA: {{producto.categoria}}</b>
                    </p>
                    <p class="mt-2">
                        {{producto.descripcion_producto |safe}}
                    </p>
                </div>
                <div>

                    <div class="d-flex justify-content-between">
                        <div class="d-flex flex-column justify-content-center">
                            <div><span><strong class="pr-2">PRECIO:</strong> <strong
                                        class="h5">${{producto.precio|floatformat:2}}</strong></span></div>
                        </div>
                        {% if user.is_authenticated %}
                        <a type="button" class="btn btn-primary" href="{% url 'TIENDA:carrito' producto.id%}">Agregar al
                            Carrito</a>
                        {% else %}
                        <a type="button" class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}">Agregar
                            al Carrito</a>
                        {% endif %}


                    </div>


                </div>


            </div>
        </div>
    </div>
</div>



{% endblock %}

PROYECTO/PROYECTO/TIENDA/templates/page/producto_alta.html
{% extends "page/layout.html" %}

{% block content %}

<h2 class="text-center mt-2 mb-5">ALTA DE PRODUCTOS</h2>

<form enctype="multipart/form-data" action="{% url 'TIENDA:producto_alta' %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="categoria_input" class="col-sm-2 col-form-label">Categoria:</label> {{ form.categoria }}
        {{ form.categoria.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input" class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }}
        {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input" class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }}
        {{ form.precio.errors }}
    </div>
    <div class="form-group row mb-4">
        <label for="imagen_input" class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }}
        {{ form.imagen.errors }}
    </div>

    <div class="form-group row" class="col-sm-2 col-form-label">
        <label for="descripcion_input"><span class="mx-4">Descripcion:</span></label>
        {{ form.descripcion_producto }} {{ form.descripcion_producto.errors }}
        <script>$("#id_descripcion").removeAttr("required");</script>
    </div>
    <div class="col-auto text-center">
        <a class="btn btn-secondary" type="button" href="{% url 'TIENDA:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Añadir">
    </div>

</form>

{% endblock %}

PROYECTO/PROYECTO/TIENDA/templates/page/producto_editar.html
{% extends "page/layout.html" %}

{% block content %}


<h2 class="text-center mt-1 mb-5">MODIFICAR PRODUCTOS</h2>


<form enctype="multipart/form-data" action="{% url 'TIENDA:producto_editar' producto.id%}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="categoria_input" class="col-sm-2 col-form-label">Categoria:</label> {{ form.categoria }}
        {{ form.categoria.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input" class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }}
        {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input" class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }}
        {{ form.precio.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input" class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }}
        {{ form.imagen.errors }}
    </div>
    <img class="mb-2 rounded mx-auto d-block" style="width: 30vw;" src='{{producto.imagen.url}}'>

    <div class="form-group row" class="col-sm-2 col-form-label">
        <label for="descripcion_input"><span class="mx-4">Descripcion:</span></label>
        {{ form.descripcion_producto }} {{ form.descripcion_producto.errors }}
        <script>$("#id_descripcion").removeAttr("required");</script>
    </div>
    <div class="col-auto text-center">
        <a class="btn btn-secondary" type="button" href="{% url 'TIENDA:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
        <a type="button" class="btn btn-primary" href="{% url 'TIENDA:producto_eliminar' producto.id%}">Eliminar</a>
    </div>

</form>
{% endblock %}